name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main  # Run the workflow on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python and dependencies
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Build and push the Docker image
    - name: Build and push Docker image
      run: |
        docker build -t ismayil14/movie-recommendation-api:latest .
        docker push ismayil14/movie-recommendation-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step 1: Pull and run the Docker image on the server
    - name: Deploy Docker container
      run: |
        docker pull ismayil14/movie-recommendation-api:latest
        docker run -d -p 5000:5000 -p 8501:8501 ismayil14/movie-recommendation-api:latest
